export const ERROR_MESSAGES = {
  UNAUTHORIZED: 'Unauthorized',
  PROJECT_NOT_FOUND: 'Project not found',
  SCENE_NOT_FOUND: 'Scene not found',
  INTERNAL_SERVER_ERROR: 'Internal server error',
  MISSING_API_KEY: 'Server configuration error: API key not set',
  MISSING_PROMPT: 'Prompt is required',
  MISSING_TEXT: 'Text is required',
  MISSING_TITLE: 'Title is required',
  MISSING_INPUT_TEXT: 'Input text is required',
  MISSING_SCENES: 'Scenes array is required',
  MISSING_TASK_ID: 'Task ID is required',
  TEXT_TOO_SHORT: 'Input text must be at least 50 characters',
  TEXT_TOO_LONG: 'Text must be less than 1000 characters',
  UPLOAD_FAILED: 'Failed to upload file',
  UNKNOWN_ERROR: 'Unknown error',
  REQUEST_FAILED: 'Request failed',
  GENERATE_SCRIPT_FAILED: 'Failed to generate script',
  CREATE_PROJECT_FAILED: 'Failed to create project',
  SAVE_SCENES_FAILED: 'Failed to save scenes',
  FETCH_NOT_OK: 'Fetch not ok',
  MINIMAX_API_KEY_MISSING: 'MINIMAX_API_KEY is not set',
  SUPABASE_SERVICE_ROLE_KEY_MISSING: 'SUPABASE_SERVICE_ROLE_KEY is not set',
  DATABASE_URL_MISSING: 'DATABASE_URL or POSTGRES_URL is not set',
  AUTH_PROVIDER_MISSING: 'useAuth must be used within an AuthProvider',
} as const;
