import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { ScriptOutput } from '@/types';

interface ScriptPreviewProps {
  script: ScriptOutput | null;
}

export function ScriptPreview({ script }: ScriptPreviewProps) {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Generated Script</CardTitle>
        <CardDescription>Preview the script generated by AI</CardDescription>
      </CardHeader>
      <CardContent>
        {!script ? (
          <div className="flex h-[400px] items-center justify-center text-gray-400">
            <p>Generate a script to see the result here</p>
          </div>
        ) : (
          <div className="space-y-6">
            <div>
              <h3 className="text-lg font-semibold">{script.title}</h3>
              <p className="mt-1 text-sm text-gray-500">Music: {script.music_suggestion}</p>
            </div>

            <div className="space-y-4">
              {script.scenes.map((scene, index) => (
                <div key={index} className="rounded-lg bg-gray-50 p-4">
                  <div className="mb-2 flex items-center gap-2">
                    <span className="text-sm font-medium text-gray-500">Scene {index + 1}</span>
                  </div>
                  <p className="mb-2 text-sm">{scene.text}</p>
                  <p className="text-xs text-gray-500 italic">Visual: {scene.visual_description}</p>
                </div>
              ))}
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
